#!/usr/bin/env bash

function checkCommand()
{
    command -v "$1" > /dev/null || {
        echo "cannot find command '$1'" >&2
        false
    }
}

function checkRootPrivileges()
{
    (( !EUID )) || {
        echo "requires root privileges" >&2
        false
    }
}

function confirmYesNo()
{
    local value
    while :; do
        read -ep "$1 (y/N): " value
        value=${value:-N}
        case $value in
            Y | y) true; return ;;
            N | n) false; return ;;
            *) echo "invalid input: $value" ;;
        esac
    done
}

# https://stackoverflow.com/a/5032641
function strIndex()
{
    local x=${1%%$2*}
    [[ $x == $1 ]] && echo -1 || echo "${#x}"
}
